@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Aug 24 00:14:49 +0530 2026
REM SW Build 6299465 on Fri Nov 14 19:35:11 GMT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
set SIM_VER_XSIM=
set GCC_VER_XSIM=9.3.0
REM simulate design
echo "xsim Pipeline_top_tb_behav -key {Behavioral:sim_1:Functional:Pipeline_top_tb} -tclbatch Pipeline_top_tb.tcl -view E:/Electronics/Verilog Projects/RISC-V_Pipelined_Core/Pipeline_top_tb_behav.wcfg -log simulate.log"
call xsim  Pipeline_top_tb_behav -key {Behavioral:sim_1:Functional:Pipeline_top_tb} -tclbatch Pipeline_top_tb.tcl -view E:/Electronics/Verilog Projects/RISC-V_Pipelined_Core/Pipeline_top_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
